#自动调用api保活，加密版
name: Auto Api Secret

on: 
  release:
    types: [published, created, edited]
  push:
    tags:
      - 'v*'
    branches: 
      - master
  schedule:
    - cron: '0 0-8 * * *'
  workflow_dispatch:
    inputs:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install requests
        pip install telepot
    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id 提供
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # secrets_key 提供
      run: | 
        cp 1.py 2.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '10 r configid.txt' 2.py
        sed -i '12 r configkey.txt' 2.py
    - name: Test Api #Api调用
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python 2.py ${{ secrets.TELEBOT_TOKEN }} ${{ secrets.CHAT_ID }}
    - name: Delete secrets config #删除机密
      run: | 
        rm -f 2.py
        rm -f configid.txt
        rm -f configkey.txt    
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --global user.email '${{ secrets.EMAIL }}'
        git config --global user.name ccknbc
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
